CREATE TABLE `CARGOS` (
  `COD_CARGO` INT PRIMARY KEY,
  `NOMBRE_CARGO` varchar(100),
  `SUELDO_BASICO` decimal(10,2)
);

CREATE TABLE `DIRECCION` (
  `ID_DIRECCION` INT PRIMARY KEY,
  `DEPARTAMENTO` varchar(100),
  `PROVINCIA` varchar(100),
  `DETALLE_DIRECCION` varchar(150),
  `REFERENCIA` varchar(150)
);

CREATE TABLE `SEDE` (
  `COD_SEDE` INT PRIMARY KEY,
  `AFORO` INT,
  `NUM_PISOS` INT,
  `UBICACION` varchar(150),
  `ID_DIRECCION` INT
);

CREATE TABLE `EMPLEADO` (
  `COD_EMPLE` INT PRIMARY KEY,
  `NOMBRES` varchar(100),
  `APELLIDOS` varchar(100),
  `DNI_EMPLE` varchar(20) UNIQUE,
  `ESTADO_CIVIL` varchar(50),
  `NIVEL_EDUCA` varchar(50),
  `TELEFONO` varchar(20),
  `EMAIL` varchar(100),
  `FECHA_INGRESO` date,
  `ID_DIRECCION` INT,
  `COD_CARGO` INT,
  `COD_SEDE` INT
);

CREATE TABLE `CLIENTE` (
  `ID_CLIENTE` INT PRIMARY KEY,
  `NOMBRES` varchar(100),
  `APELLIDOS` varchar(100),
  `FONO` varchar(20),
  `EMAIL` varchar(100)
);

CREATE TABLE `DIRECCION_CLIENTE` (
  `ID_CLIENTE` INT,
  `ID_DIRECCION` INT,
  `TIPO` varchar(50),
  `primary` key(ID_CLIENTE,ID_DIRECCION)
);

CREATE TABLE `CATEGORIAS` (
  `COD_CATE` INT PRIMARY KEY,
  `NOMBRE` varchar(100)
);

CREATE TABLE `PRODUCTO` (
  `ID_PRODUCTO` INT PRIMARY KEY,
  `DESCRIPCION` varchar(150),
  `PRECIO_VENTA` decimal(10,2),
  `STOCK_MINIMO` INT,
  `STOCK_ACTUAL` INT,
  `COD_CATE` INT,
  `COD_SEDE` INT
);

CREATE TABLE `BOLETA` (
  `NUM_BOLETA` INT PRIMARY KEY,
  `FECHA_EMI` date,
  `ID_CLIENTE` INT,
  `COD_EMPLE` INT,
  `ESTADO_BOLETA` varchar(50),
  `TOTAL` decimal(10,2)
);

CREATE TABLE `DETALLEBOLETA` (
  `NUM_BOLETA` INT,
  `ID_PRODUCTO` INT,
  `CANTIDAD` INT,
  `IMPORTE` decimal(10,2),
  `IGV` decimal(10,2),
  `primary` key(NUM_BOLETA,ID_PRODUCTO)
);

ALTER TABLE `SEDE` ADD FOREIGN KEY (`ID_DIRECCION`) REFERENCES `DIRECCION` (`ID_DIRECCION`);

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`ID_DIRECCION`) REFERENCES `DIRECCION` (`ID_DIRECCION`);

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`COD_CARGO`) REFERENCES `CARGOS` (`COD_CARGO`);

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`COD_SEDE`) REFERENCES `SEDE` (`COD_SEDE`);

ALTER TABLE `DIRECCION_CLIENTE` ADD FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID_CLIENTE`);

ALTER TABLE `DIRECCION_CLIENTE` ADD FOREIGN KEY (`ID_DIRECCION`) REFERENCES `DIRECCION` (`ID_DIRECCION`);

ALTER TABLE `PRODUCTO` ADD FOREIGN KEY (`COD_CATE`) REFERENCES `CATEGORIAS` (`COD_CATE`);

ALTER TABLE `PRODUCTO` ADD FOREIGN KEY (`COD_SEDE`) REFERENCES `SEDE` (`COD_SEDE`);

ALTER TABLE `BOLETA` ADD FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID_CLIENTE`);

ALTER TABLE `BOLETA` ADD FOREIGN KEY (`COD_EMPLE`) REFERENCES `EMPLEADO` (`COD_EMPLE`);

ALTER TABLE `DETALLEBOLETA` ADD FOREIGN KEY (`NUM_BOLETA`) REFERENCES `BOLETA` (`NUM_BOLETA`);

ALTER TABLE `DETALLEBOLETA` ADD FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO` (`ID_PRODUCTO`);
